allowBuilds:
  ' ': true
  /: true
  '@': true
  '@prisma/engines': true
  a: true
  e: true
  g: true
  h: true
  i: true
  m: true
  n: true
  p: true
  prisma: true
  r: true
  s: true
  sharp: true
